spring:
  profiles:
    #include: application-gemini.yaml
    group:
      openai:
        - application-openai
      ollama:
        - application-ollama
      vertex:
        - application-vertex

    active: openai


#    mcp:
#      client:
#        sse:
#          connections:
#            server1:
#              url: http://localhost:8081
#            server2:
#              url: http://otherserver:8081
#              sse-endpoint: /custom-sse

