spring:
  ai:
    ollama:
      chat:
        model: gemma3:1b
        options:
          model:  gemma3:1b
        enabled: true

#    azure:
#      openai:
#        chat:
#          options:
#            function-callbacks:
#              - name: "functionName1"
#                description: "Description of what function1 does"
#                input-type-schema: |
#                  {
#                    "type": "object",
#                    "properties": {
#                      "param1": {
#                        "type": "string"
#                      }
#                    }
#                  }
#              - name: "functionName2"
#                description: "Description of what function2 does"
#                input-type-schema: |
#                  {
#                    "type": "object",
#                    "properties": {
#                      "param2": {
#                        "type": "integer"
#                      }
#                    }
#                  }
