spring:
  profiles:
    #include: application-openai.yaml
    group:
      openai:
        - application-openai
      ollama:
        - application-ollama
      vertex:
        - application-vertex

    active: openai

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: 123456
    username: postgres
  sql:
    init:
      mode: always
      schema-locations: "classpath*:db/postgres/schema.sql"
      data-locations: "classpath*:db/postgres/data.sql"

#    mcp:
#      client:
#        sse:
#          connections:
#            server1:
#              url: http://localhost:8081
#            server2:
#              url: http://otherserver:8081
#              sse-endpoint: /custom-sse

