server:
  port: 8081
  servlet:
    context-path: /springai
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  ai:
    openai:
      api-key: ${GEMINI_API_KEY}
      chat: # By default its true, this triggers the autoconfiguration.
        options:
          model: gemini-2.5-flash #gpt-4o
          temperature: 1.0
          max_completion_tokens: 2000
    vectorstore:
      pgvector:
        initialize-schema: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
    hikari:
      minimumIdle: 1
      maximumPoolSize: 10
      validationQuery: SELECT 1

  flyway:
    enabled: false
ingestion:
  enabled: false