server:
  port: 8081
  servlet:
    context-path: /springai
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  ai:
    ollama:
      chat:
        options:
          model: llama3

