server:
  port: 8083
  servlet:
    context-path: /springai
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  ai:
    openai:
      api-key: ${OPENAI_KEY}
      chat: # By default its true, this triggers the autoconfiguration.
        options:
          model: gpt-4.1
          temperature: 1.0
          max_completion_tokens: 2000
#          response-format: json
      image:
        api-key: ${OPENAI_KEY}
        options:
          quality: "hd"
          n: 1
          height: 1024
          width: 1024
          model: gpt-image-1 # gpt-image-1, dall-e-2, dall-e-3
          responseFormat: url # url, b64_json
          style: natural # natural, vivid
      audio:
        speech:
          options:
            speed: 1.0
            model: "tts-1" #tts-1, tts-1-hd or gpt-4o-mini-tts
            response-format: "mp3"
            voice: "nova" #alloy, echo, fable, onyx, nova, shimmer, sage, coral, and ash
        transcription:
          options:
            prompt: Extract text from the file.
#            response-format: JSON
            model: "whisper-1" #"whisper-1", gpt-4o-mini-transcribe, gpt-4o-transcribe